### ISSUE TITLE
1.6rc1 build error: HOST_NAME_MAX not defined

### ISSUE THREAD

**Issue by petere** [markokr/pgbouncer-dev#40]
`HOST_NAME_MAX` (5d2b23bb46285ca7099a6605d5e47af49cb20148) is not defined on OS X, and apparently on other BSD-like systems, so the build fails.

Similar bugs:

- https://dev.lsstcorp.org/trac/ticket/1247
- https://github.com/facebook/hhvm/issues/2141

**Comment by markokr** [comment]
fixed
